//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Student_Registration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int StuId { get; set; }
        public string StuName { get; set; }
        public string StuLastName { get; set; }
        public string StuGmail { get; set; }
        public string StuImage { get; set; }
        public string StuAddress { get; set; }
    }
}
